### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by bjw-s** [k8s-at-home/docs#10]
# Details

**What steps did you take and what happened:**

Open http://docs.k8s-at-home.com/our-helm-charts/development/unit-tests/

**What did you expect to happen:**

The images should render correctly

**Anything else you would like to add:**

The images throw a 404.

**Additional Information:**

The images have probably not been migrated from the old wiki to the new docs setup.

**Comment by onedr0p** [comment]
Crap forgot to upload these, I have them on my desktop.

**Comment by nicholaswilde** [comment]
@onedr0p If you upload the images somewhere, I can integrate them into the docs. I can't the the images posted anywhere by looking at the old wiki.

**Comment by onedr0p** [comment]
@nicholaswilde they can be found here https://github.com/k8s-at-home/charts/pull/657
