### ISSUE TITLE
Consolidated documentation for handling edge hardware in K8s

### ISSUE THREAD

**Issue by lazyoldbear** [k8s-at-home/docs#13]
Pulling it as a new issue to ignore, reject or consider in future. I can't lead it, but will gladly review or act as a minor contributor.

As we see, the variety of different tools necessary to provision hardware resources to pods is depressing. Alternative "quick" ways like privileged containers are dangerous and don't solve everything. 

As a consideration for future, it might be beneficial to write a little note about how hardware gets attached to containers. There is intel GPU thing, node-feature-discovery, smarter device manager. And also an old practice of privileged containers with automation tools directly using host resources. And the topic is not that complicated. 

_Originally posted by @lazyoldbear in https://github.com/k8s-at-home/charts/issues/532#issuecomment-773294191_

**Comment by nicholaswilde** [comment]
I'd like to start working on this doc but I'm struggling to figure out where to start. I'm looking at [intel-gpu-plugin](https://github.com/k8s-at-home/charts/tree/master/charts/intel-gpu-plugin), [smarter-device-manager](https://github.com/k8s-at-home/charts/tree/master/charts/smarter-device-manager), and [node-feature-discovery](https://github.com/k8s-at-home/charts/tree/master/charts/node-feature-discovery). All of these are using custom templates that are not pointing to the common library. Do I just point to these charts as examples? Any direction would be greatly appreciated.

**Comment by lazyoldbear** [comment]
The main question is how to make use of very stateful and host-bound assets (hardware) to stateless-ish and host-independent (ish) platform (Kubernetes). 
Industry consensus is to use different kinds of smart metadata to decouple these things in a way that makes peculiar hardware similar to compute resources (CPU, memory, ephemeral storage) and persistent storage. 

The problem is that conventional learning path (run on Linux, run "in Docker", try docker-compose, end up with k8s) leans to the "easiest" way, which is to molest the containers in pods through direct blunt access to host resources. 
In my opinion, what is missing, is an introduction to the matter. 

One (not the only one!) possible take on that I can think of, is the following document structure:

1. Brief reminder on the nature of containers. 
2. Accessing hardware in `docker run` case.
3. Brief intro into generic orchestration approaches, the essence of Kubernetes.
4. Why `docker run` patterns are not good for K8s.
5. It is not scary at all.
6. Considerations of scaling up (perhaps, introducing some edge stuff) with practical examples (little Respberry box in a garage or in a mountain cabin).

BTW, I missed the moment when node-feature-discovery disappeared, but it may be available elsewhere.
