### ISSUE TITLE
Documentation update for common storage

### ISSUE THREAD

**Issue by allenporter** [k8s-at-home/docs#40]
# Details

**What steps did you take and what happened:**

When trying to understand the breaking changes in the common library, I had trouble with additional volumes.
I believe that the examples here 
https://github.com/k8s-at-home/docs/edit/main/docs/our-helm-charts/common-library-storage.md
all need to be updated `enabled: true`.  Is that right? I wanted to confirm I understood this right before sending an update.

**What did you expect to happen:**

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
Yeah, you're right, those need to have `enabled: true` as well. I completely forgot about that 😓
