### ISSUE TITLE
List Is Not Nested On Docs Site

### ISSUE THREAD

**Issue by dcplaya** [k8s-at-home/docs#48]
https://github.com/k8s-at-home/docs/blob/b5bdbebd33df3df574e7132f24c039585cfd7c9a/docs/our-container-images/permissions.md#L47-L52

This looks weird on the docs site, list isn't nested (See attached picture). I was going to submit a PR but looking at the markdown on GitHub, the list is nested so I am not sure what is wrong. Very minor but I can see it causing confusion for someone reading it

http://docs.k8s-at-home.com/our-container-images/permissions/#optional-configuration
![image](https://user-images.githubusercontent.com/1105320/135699953-7f787d90-bb08-4d83-93cc-2e698ab1aa32.png)

**Comment by onedr0p** [comment]
Could be a mkdocs thing, I'll take a look!

**Comment by onedr0p** [comment]
Updated!
