### ISSUE TITLE
Unable to create a new chart using tutorial

### ISSUE THREAD

**Issue by insuusvenerati** [k8s-at-home/docs#50]
# Details

- When creating a new chart using the docs (https://docs.k8s-at-home.com/our-helm-charts/development/creating-a-new-chart/), the repo url is missing from the `git clone` command. 

- The `chart:create` command is not found
```
❯ task chart:create CHART_TYPE=incubator CHART=chart-name
task: Available tasks for this project:
* chart:ct-lint:                run `ct lint` on your chart code
* chart:helm-docs:              generate helm-docs
* chart:lint:                   lint your chart code
* deps:distrib-requirements:    Check needed distribution packages
* deps:helm:                    Install helm client
* deps:install:                 Install all developer dependencies
* deps:need:                    Check needed binary is present
* deps:pre-commit:              Install a precommit pip package
task: Task "chart:create" not found
```

**What did you expect to happen:**

A directory called `chart-name` should be created in the `incubator` folder.

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
I just did a new install of Task on my Mac (`brew install go-task/tap/go-task`), and did a brand new checkout of the [`k8s-at-home/charts`](https://github.com/k8s-at-home/charts/) repository.

Then from the root of that repository I run `task`, and I see this output:
```console
task: Available tasks for this project:
* chart:create: 		create new chart
* chart:ct-lint: 		run `ct lint` on your chart code
* chart:dependency-cleanup: 	clean up chart dependencies
* chart:helm-docs: 		generate helm-docs
* chart:lint: 			lint your chart code
* deps:distrib-requirements: 	Check needed distribution packages
* deps:go-replace: 		Install go-replace
* deps:install: 		Install all developer dependencies
* deps:need: 			Check needed binary is present
```

As you can see, the `chart:create` task is visible there.

My Task version is:
```console
❯ task --version
Task version: v3.9.2 (h1:lej66zb32AL491eELVc9JK7Hey8l4AtyBaQ1pJ4Iu7E=)
```

**Comment by bjw-s** [comment]
I do see that the `git clone` command in the docs is missing the repo URL, I've added that.

**Comment by insuusvenerati** [comment]
Turns out I was cloning the wrong repo. Adding the repo to the `git clone` command fixed it for me. Thanks!
